# =============================
# 実験設定ファイル
# =============================

scenario:
  data_scenario_id: "data_scenario_4"
  model_id: "linear"
  model_scenario_id: "model_scenario_1"

dataset:
    target_number: 200
    source_number: 200

hyperparameters:
    alpha: 1
    split_ratio: 1
    n_trial: 1000
    n_split: 5
    n_features: 10
    source_borrow_number: 100
    true_value: 1.0
  
  
